version: '3'
services:
  back:
    build: ./back
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./back:/myapp
      - bundle:/usr/local/bundle
    depends_on:
      - db
  db:
    image: mariadb:latest
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes" #パスワードなしにしたい場合はこれ
    ports:
      - '3306:3306'
    volumes:
      - "mariadb_data:/var/lib/mysql"
volumes:
  bundle:
  mariadb_data:
